name: Sample Consumer Workflow

on:
  push:
    paths:
      - 'samples/consumer/**'
      - '.github/workflows/sample_consumer.yml'

env:
  PACT_BROKER_BASE_URL: ${{ secrets.PACT_BROKER_BASE_URL }}
  PACT_BROKER_TOKEN: ${{ secrets.PACT_BROKER_TOKEN }}
  PACTICIPANT: "Consumer"

jobs:
  test-and-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Build
        run: dotnet build samples/consumer/Consumer.sln

      - name: Test
        run: dotnet test samples/consumer/Consumer.sln

      - name: Publish Pacts
        run: |
          docker run --rm \
           -w ${PWD} \
           -v ${PWD}:${PWD} \
           -e PACT_BROKER_BASE_URL \
           -e PACT_BROKER_TOKEN \
           pactfoundation/pact-cli:latest \
           publish \
           ${PWD}/samples/consumer/pacts \
           --consumer-app-version ${GITHUB_SHA} \
           --branch ${GITHUB_REF#refs/heads/}

      - name: Can I Deploy?
        run: |
          docker run --rm \
           -e PACT_BROKER_BASE_URL \
           -e PACT_BROKER_TOKEN \
           pactfoundation/pact-cli:latest \
           broker can-i-deploy \
           --pacticipant ${PACTICIPANT} \
           --version ${GITHUB_SHA} \
           --to-environment production \
           --retry-while-unknown 5 \
           --retry-interval 10
        continue-on-error: true # Allow failure if provider not present yet

      - name: Record Deployment
        if: success()
        run: |
          docker run --rm \
           -e PACT_BROKER_BASE_URL \
           -e PACT_BROKER_TOKEN \
           pactfoundation/pact-cli:latest \
           broker record-deployment \
           --pacticipant ${PACTICIPANT} \
           --version ${GITHUB_SHA} \
           --environment production
